### ISSUE TITLE
User can view a list of house for sale by city name

### ISSUE THREAD

**Issue by Han-Zhang-fuze** [Han-Zhang-fuze/ajax-project#1]
## 💰 Motivation

User can see what's the housing price at the city they care about

## 📐 Plan

make a search bar to gather user input and show a list of houses for sale according to user input 

## 🖼️ Wireframes

![Screen Shot 2022-06-13 at 3 23 42 PM](https://user-images.githubusercontent.com/103379415/173457210-ce06235f-9f41-4c43-83e4-710d588a994c.png)

## ✅ Task List

- [x] Create html and css, use dummy picture for the listing page for now
- [x] Make a search bar to gather user input
- [x] Store user input value to a variable then use that variable to modify API calling function 
- [x] Replace the dummy picture in the listing page, use the data in the api to generate a DOM tree that creates a list of house for sale  
- [x] `setAttribute('data-propertyID', xhr.response.properties[i].property_id)` to each listing for future use
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
