### ISSUE TITLE
User can view the detail of a house for sale 

### ISSUE THREAD

**Issue by Han-Zhang-fuze** [Han-Zhang-fuze/ajax-project#2]
## 💰 Motivation

Once a list of house for sale is generated, people wants to see the detail of each listing. 

## 📐 Plan

Display the detail of a listing in a 'new page'

## 🖼️ Wireframes

![Screen Shot 2022-06-13 at 3 41 36 PM](https://user-images.githubusercontent.com/103379415/173459437-f97e7562-09d8-4192-ba11-9deb0f580f36.png)

## ✅ Task List

- [x] Finish the HTML and CSS first, use dummy picture and data to hold the image for now 
- [x] get the property id from API when user click a certain house for sale from Listing page
- [x]  replace the dummy picture and data, use the property id to find other details about the listing, DOM create those data
- [x] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [x] Test all functionality again in a private browsing session.
- [x] Fix all errors.
