### ISSUE TITLE
User can save a listing to their favorite list

### ISSUE THREAD

**Issue by Han-Zhang-fuze** [Han-Zhang-fuze/ajax-project#3]
## 💰 Motivation

User want to save a listing to their favorite list when they wants to see it again next time or people can compare one listing to the other easily

## 📐 Plan

Create favorite icon to each listing and listing detail, store the favorited to an array variable 

## 🖼️ Wireframes

![Screen Shot 2022-06-13 at 4 06 06 PM](https://user-images.githubusercontent.com/103379415/173463885-04586238-f988-4f0a-b0c7-21cdddd498b0.png)

## ✅ Task List

- [ ] create a heart icon to each listing and listing detail.
- [ ] when user click the heart icon, the icon should change from holo to solid
- [ ] declare an array variable `favoriate` to data model which will store the favorite listing information to the array variable.
- [ ] console.log to see if the information has been stored. 
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
