### ISSUE TITLE
User can view their favorite list

### ISSUE THREAD

**Issue by Han-Zhang-fuze** [Han-Zhang-fuze/ajax-project#4]
## 💰 Motivation

People wants to view their favorite list once they add their listing to the favorite 

## 📐 Plan

Create a favorite list

## 🖼️ Wireframes

![Screen Shot 2022-06-13 at 4 45 26 PM](https://user-images.githubusercontent.com/103379415/173465185-ce0be7ad-4271-46e1-bc3d-2b84b88e12f5.png)

## ✅ Task List

- [ ] Dom create a list of house that user favorites from the variable that stored all listing that user favorited in a 'new page'
- [ ] Remove all CSS styling that had no affect or was otherwise unnecessary.
- [ ] Test all functionality again in a private browsing session.
- [ ] Fix all errors.
